import os
import pytest

def test_health_check(client):
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["status"] == "ok"

def test_unauthorized_access(client):
    response = client.post("/extract")
    assert response.status_code == 401

def test_empty_file(client, api_key, sample_path):
    # Create an empty file
    empty_file_path = os.path.join(sample_path, "empty.txt")
    with open(empty_file_path, "wb") as f:
        pass
    
    with open(empty_file_path, "rb") as f:
        response = client.post(
            "/extract",
            files={"file": ("empty.txt", f)},
            headers={"X-API-Key": api_key}
        )
    assert response.status_code == 400

def test_unsupported_format(client, api_key, sample_path):
    # Create an unsupported format (e.g., .exe or .zip)
    unsupported_path = os.path.join(sample_path, "test.zip")
    with open(unsupported_path, "wb") as f:
        f.write(b"PK\x03\x04" + b"\0" * 20)
    
    with open(unsupported_path, "rb") as f:
        response = client.post(
            "/extract",
            files={"file": ("test.zip", f)},
            headers={"X-API-Key": api_key}
        )
    assert response.status_code == 415

def test_file_too_large(client, api_key, sample_path):
    large_file_path = os.path.join(sample_path, "large.txt")
    # Ensure large file exists (generated by create_samples.py)
    if not os.path.exists(large_file_path):
        pytest.skip("Large file sample not found")

    with open(large_file_path, "rb") as f:
        response = client.post(
            "/extract",
            files={"file": ("large.txt", f)},
            headers={"X-API-Key": api_key}
        )
    assert response.status_code == 413

@pytest.mark.parametrize("filename,expected_type", [
    ("test.txt", "document"),
    ("test.docx", "document"),
    ("test.xlsx", "document"),
    ("test.pptx", "document"),
    ("test_text.pdf", "pdf_text"),
])
def test_successful_extractions(client, api_key, sample_path, filename, expected_type):
    file_path = os.path.join(sample_path, filename)
    if not os.path.exists(file_path):
        pytest.skip(f"Sample {filename} not found")

    with open(file_path, "rb") as f:
        response = client.post(
            "/extract",
            files={"file": (filename, f)},
            headers={"X-API-Key": api_key}
        )
    
    assert response.status_code == 200
    data = response.json()
    assert data["type"] == expected_type
    assert "text" in data
    assert len(data["text"]) > 0

def test_batch_extraction(client, api_key, sample_path):
    files = [
        ("files", ("test.txt", open(os.path.join(sample_path, "test.txt"), "rb"))),
        ("files", ("test.docx", open(os.path.join(sample_path, "test.docx"), "rb"))),
    ]
    
    response = client.post(
        "/extract/batch",
        files=files,
        headers={"X-API-Key": api_key}
    )
    
    assert response.status_code == 200
    data = response.json()
    assert data["total"] == 2
    assert len(data["results"]) == 2
    assert data["status"] == "completed"
