/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInLinkRouteImport } from './routes/sign-in-link'
import { Route as SignInIllustrationRouteImport } from './routes/sign-in-illustration'
import { Route as SignInCoverRouteImport } from './routes/sign-in-cover'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ErrorMaintenanceRouteImport } from './routes/error-maintenance'
import { Route as Error500RouteImport } from './routes/error-500'
import { Route as Error429RouteImport } from './routes/error-429'
import { Route as Error404RouteImport } from './routes/error-404'
import { Route as Error403RouteImport } from './routes/error-403'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreditRouteImport } from './routes/credit'
import { Route as AuthLockRouteImport } from './routes/auth-lock'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as R2StepVerificationCodeRouteImport } from './routes/2-step-verification-code'
import { Route as R2StepVerificationRouteImport } from './routes/2-step-verification'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions.index'
import { Route as TrackerIndexRouteImport } from './routes/tracker.index'
import { Route as PlanningIndexRouteImport } from './routes/planning.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as CreditIndexRouteImport } from './routes/credit.index'
import { Route as TrackerTextRouteImport } from './routes/tracker.text'
import { Route as TrackerPhotoRouteImport } from './routes/tracker.photo'
import { Route as TrackerInputRouteImport } from './routes/tracker.input'
import { Route as TrackerImageRouteImport } from './routes/tracker.image'
import { Route as TrackerFileRouteImport } from './routes/tracker.file'
import { Route as TrackerAudioRouteImport } from './routes/tracker.audio'
import { Route as PlanningSubscriptionsRouteImport } from './routes/planning.subscriptions'
import { Route as PlanningGoalsRouteImport } from './routes/planning.goals'
import { Route as PlanningBudgetRouteImport } from './routes/planning.budget'
import { Route as GamificationStreakRouteImport } from './routes/gamification.streak'
import { Route as GamificationStoreRouteImport } from './routes/gamification.store'
import { Route as GamificationQuestsRouteImport } from './routes/gamification.quests'
import { Route as DashboardAssetsRouteImport } from './routes/dashboard.assets'
import { Route as CreditPaylaterRouteImport } from './routes/credit.paylater'
import { Route as CreditOverviewRouteImport } from './routes/credit.overview'
import { Route as CreditKtaRouteImport } from './routes/credit.kta'
import { Route as CreditKprRouteImport } from './routes/credit.kpr'
import { Route as CreditCreditCardRouteImport } from './routes/credit.credit-card'
import { Route as AccountsAccountIdRouteImport } from './routes/accounts.$accountId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInLinkRoute = SignInLinkRouteImport.update({
  id: '/sign-in-link',
  path: '/sign-in-link',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIllustrationRoute = SignInIllustrationRouteImport.update({
  id: '/sign-in-illustration',
  path: '/sign-in-illustration',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInCoverRoute = SignInCoverRouteImport.update({
  id: '/sign-in-cover',
  path: '/sign-in-cover',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorMaintenanceRoute = ErrorMaintenanceRouteImport.update({
  id: '/error-maintenance',
  path: '/error-maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const Error500Route = Error500RouteImport.update({
  id: '/error-500',
  path: '/error-500',
  getParentRoute: () => rootRouteImport,
} as any)
const Error429Route = Error429RouteImport.update({
  id: '/error-429',
  path: '/error-429',
  getParentRoute: () => rootRouteImport,
} as any)
const Error404Route = Error404RouteImport.update({
  id: '/error-404',
  path: '/error-404',
  getParentRoute: () => rootRouteImport,
} as any)
const Error403Route = Error403RouteImport.update({
  id: '/error-403',
  path: '/error-403',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditRoute = CreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLockRoute = AuthLockRouteImport.update({
  id: '/auth-lock',
  path: '/auth-lock',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const R2StepVerificationCodeRoute = R2StepVerificationCodeRouteImport.update({
  id: '/2-step-verification-code',
  path: '/2-step-verification-code',
  getParentRoute: () => rootRouteImport,
} as any)
const R2StepVerificationRoute = R2StepVerificationRouteImport.update({
  id: '/2-step-verification',
  path: '/2-step-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerIndexRoute = TrackerIndexRouteImport.update({
  id: '/tracker/',
  path: '/tracker/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningIndexRoute = PlanningIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlanningRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const CreditIndexRoute = CreditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreditRoute,
} as any)
const TrackerTextRoute = TrackerTextRouteImport.update({
  id: '/tracker/text',
  path: '/tracker/text',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerPhotoRoute = TrackerPhotoRouteImport.update({
  id: '/tracker/photo',
  path: '/tracker/photo',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerInputRoute = TrackerInputRouteImport.update({
  id: '/tracker/input',
  path: '/tracker/input',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerImageRoute = TrackerImageRouteImport.update({
  id: '/tracker/image',
  path: '/tracker/image',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerFileRoute = TrackerFileRouteImport.update({
  id: '/tracker/file',
  path: '/tracker/file',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerAudioRoute = TrackerAudioRouteImport.update({
  id: '/tracker/audio',
  path: '/tracker/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningSubscriptionsRoute = PlanningSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => PlanningRoute,
} as any)
const PlanningGoalsRoute = PlanningGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => PlanningRoute,
} as any)
const PlanningBudgetRoute = PlanningBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => PlanningRoute,
} as any)
const GamificationStreakRoute = GamificationStreakRouteImport.update({
  id: '/gamification/streak',
  path: '/gamification/streak',
  getParentRoute: () => rootRouteImport,
} as any)
const GamificationStoreRoute = GamificationStoreRouteImport.update({
  id: '/gamification/store',
  path: '/gamification/store',
  getParentRoute: () => rootRouteImport,
} as any)
const GamificationQuestsRoute = GamificationQuestsRouteImport.update({
  id: '/gamification/quests',
  path: '/gamification/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAssetsRoute = DashboardAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => DashboardRoute,
} as any)
const CreditPaylaterRoute = CreditPaylaterRouteImport.update({
  id: '/paylater',
  path: '/paylater',
  getParentRoute: () => CreditRoute,
} as any)
const CreditOverviewRoute = CreditOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => CreditRoute,
} as any)
const CreditKtaRoute = CreditKtaRouteImport.update({
  id: '/kta',
  path: '/kta',
  getParentRoute: () => CreditRoute,
} as any)
const CreditKprRoute = CreditKprRouteImport.update({
  id: '/kpr',
  path: '/kpr',
  getParentRoute: () => CreditRoute,
} as any)
const CreditCreditCardRoute = CreditCreditCardRouteImport.update({
  id: '/credit-card',
  path: '/credit-card',
  getParentRoute: () => CreditRoute,
} as any)
const AccountsAccountIdRoute = AccountsAccountIdRouteImport.update({
  id: '/$accountId',
  path: '/$accountId',
  getParentRoute: () => AccountsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/2-step-verification': typeof R2StepVerificationRoute
  '/2-step-verification-code': typeof R2StepVerificationCodeRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/achievements': typeof AchievementsRoute
  '/activity': typeof ActivityRoute
  '/assets': typeof AssetsRoute
  '/auth-lock': typeof AuthLockRoute
  '/credit': typeof CreditRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/error-403': typeof Error403Route
  '/error-404': typeof Error404Route
  '/error-429': typeof Error429Route
  '/error-500': typeof Error500Route
  '/error-maintenance': typeof ErrorMaintenanceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/planning': typeof PlanningRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-in-cover': typeof SignInCoverRoute
  '/sign-in-illustration': typeof SignInIllustrationRoute
  '/sign-in-link': typeof SignInLinkRoute
  '/sign-up': typeof SignUpRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/credit/credit-card': typeof CreditCreditCardRoute
  '/credit/kpr': typeof CreditKprRoute
  '/credit/kta': typeof CreditKtaRoute
  '/credit/overview': typeof CreditOverviewRoute
  '/credit/paylater': typeof CreditPaylaterRoute
  '/dashboard/assets': typeof DashboardAssetsRoute
  '/gamification/quests': typeof GamificationQuestsRoute
  '/gamification/store': typeof GamificationStoreRoute
  '/gamification/streak': typeof GamificationStreakRoute
  '/planning/budget': typeof PlanningBudgetRoute
  '/planning/goals': typeof PlanningGoalsRoute
  '/planning/subscriptions': typeof PlanningSubscriptionsRoute
  '/tracker/audio': typeof TrackerAudioRoute
  '/tracker/file': typeof TrackerFileRoute
  '/tracker/image': typeof TrackerImageRoute
  '/tracker/input': typeof TrackerInputRoute
  '/tracker/photo': typeof TrackerPhotoRoute
  '/tracker/text': typeof TrackerTextRoute
  '/credit/': typeof CreditIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/planning/': typeof PlanningIndexRoute
  '/tracker/': typeof TrackerIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/2-step-verification': typeof R2StepVerificationRoute
  '/2-step-verification-code': typeof R2StepVerificationCodeRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/achievements': typeof AchievementsRoute
  '/activity': typeof ActivityRoute
  '/assets': typeof AssetsRoute
  '/auth-lock': typeof AuthLockRoute
  '/error-403': typeof Error403Route
  '/error-404': typeof Error404Route
  '/error-429': typeof Error429Route
  '/error-500': typeof Error500Route
  '/error-maintenance': typeof ErrorMaintenanceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-in-cover': typeof SignInCoverRoute
  '/sign-in-illustration': typeof SignInIllustrationRoute
  '/sign-in-link': typeof SignInLinkRoute
  '/sign-up': typeof SignUpRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/credit/credit-card': typeof CreditCreditCardRoute
  '/credit/kpr': typeof CreditKprRoute
  '/credit/kta': typeof CreditKtaRoute
  '/credit/overview': typeof CreditOverviewRoute
  '/credit/paylater': typeof CreditPaylaterRoute
  '/dashboard/assets': typeof DashboardAssetsRoute
  '/gamification/quests': typeof GamificationQuestsRoute
  '/gamification/store': typeof GamificationStoreRoute
  '/gamification/streak': typeof GamificationStreakRoute
  '/planning/budget': typeof PlanningBudgetRoute
  '/planning/goals': typeof PlanningGoalsRoute
  '/planning/subscriptions': typeof PlanningSubscriptionsRoute
  '/tracker/audio': typeof TrackerAudioRoute
  '/tracker/file': typeof TrackerFileRoute
  '/tracker/image': typeof TrackerImageRoute
  '/tracker/input': typeof TrackerInputRoute
  '/tracker/photo': typeof TrackerPhotoRoute
  '/tracker/text': typeof TrackerTextRoute
  '/credit': typeof CreditIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/planning': typeof PlanningIndexRoute
  '/tracker': typeof TrackerIndexRoute
  '/transactions': typeof TransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/2-step-verification': typeof R2StepVerificationRoute
  '/2-step-verification-code': typeof R2StepVerificationCodeRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/achievements': typeof AchievementsRoute
  '/activity': typeof ActivityRoute
  '/assets': typeof AssetsRoute
  '/auth-lock': typeof AuthLockRoute
  '/credit': typeof CreditRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/error-403': typeof Error403Route
  '/error-404': typeof Error404Route
  '/error-429': typeof Error429Route
  '/error-500': typeof Error500Route
  '/error-maintenance': typeof ErrorMaintenanceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/planning': typeof PlanningRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-in-cover': typeof SignInCoverRoute
  '/sign-in-illustration': typeof SignInIllustrationRoute
  '/sign-in-link': typeof SignInLinkRoute
  '/sign-up': typeof SignUpRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/credit/credit-card': typeof CreditCreditCardRoute
  '/credit/kpr': typeof CreditKprRoute
  '/credit/kta': typeof CreditKtaRoute
  '/credit/overview': typeof CreditOverviewRoute
  '/credit/paylater': typeof CreditPaylaterRoute
  '/dashboard/assets': typeof DashboardAssetsRoute
  '/gamification/quests': typeof GamificationQuestsRoute
  '/gamification/store': typeof GamificationStoreRoute
  '/gamification/streak': typeof GamificationStreakRoute
  '/planning/budget': typeof PlanningBudgetRoute
  '/planning/goals': typeof PlanningGoalsRoute
  '/planning/subscriptions': typeof PlanningSubscriptionsRoute
  '/tracker/audio': typeof TrackerAudioRoute
  '/tracker/file': typeof TrackerFileRoute
  '/tracker/image': typeof TrackerImageRoute
  '/tracker/input': typeof TrackerInputRoute
  '/tracker/photo': typeof TrackerPhotoRoute
  '/tracker/text': typeof TrackerTextRoute
  '/credit/': typeof CreditIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/planning/': typeof PlanningIndexRoute
  '/tracker/': typeof TrackerIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/2-step-verification'
    | '/2-step-verification-code'
    | '/accounts'
    | '/achievements'
    | '/activity'
    | '/assets'
    | '/auth-lock'
    | '/credit'
    | '/dashboard'
    | '/error-403'
    | '/error-404'
    | '/error-429'
    | '/error-500'
    | '/error-maintenance'
    | '/forgot-password'
    | '/help'
    | '/notifications'
    | '/planning'
    | '/profile'
    | '/reset-password'
    | '/settings'
    | '/sign-in'
    | '/sign-in-cover'
    | '/sign-in-illustration'
    | '/sign-in-link'
    | '/sign-up'
    | '/accounts/$accountId'
    | '/credit/credit-card'
    | '/credit/kpr'
    | '/credit/kta'
    | '/credit/overview'
    | '/credit/paylater'
    | '/dashboard/assets'
    | '/gamification/quests'
    | '/gamification/store'
    | '/gamification/streak'
    | '/planning/budget'
    | '/planning/goals'
    | '/planning/subscriptions'
    | '/tracker/audio'
    | '/tracker/file'
    | '/tracker/image'
    | '/tracker/input'
    | '/tracker/photo'
    | '/tracker/text'
    | '/credit/'
    | '/dashboard/'
    | '/planning/'
    | '/tracker/'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/2-step-verification'
    | '/2-step-verification-code'
    | '/accounts'
    | '/achievements'
    | '/activity'
    | '/assets'
    | '/auth-lock'
    | '/error-403'
    | '/error-404'
    | '/error-429'
    | '/error-500'
    | '/error-maintenance'
    | '/forgot-password'
    | '/help'
    | '/notifications'
    | '/profile'
    | '/reset-password'
    | '/settings'
    | '/sign-in'
    | '/sign-in-cover'
    | '/sign-in-illustration'
    | '/sign-in-link'
    | '/sign-up'
    | '/accounts/$accountId'
    | '/credit/credit-card'
    | '/credit/kpr'
    | '/credit/kta'
    | '/credit/overview'
    | '/credit/paylater'
    | '/dashboard/assets'
    | '/gamification/quests'
    | '/gamification/store'
    | '/gamification/streak'
    | '/planning/budget'
    | '/planning/goals'
    | '/planning/subscriptions'
    | '/tracker/audio'
    | '/tracker/file'
    | '/tracker/image'
    | '/tracker/input'
    | '/tracker/photo'
    | '/tracker/text'
    | '/credit'
    | '/dashboard'
    | '/planning'
    | '/tracker'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/2-step-verification'
    | '/2-step-verification-code'
    | '/accounts'
    | '/achievements'
    | '/activity'
    | '/assets'
    | '/auth-lock'
    | '/credit'
    | '/dashboard'
    | '/error-403'
    | '/error-404'
    | '/error-429'
    | '/error-500'
    | '/error-maintenance'
    | '/forgot-password'
    | '/help'
    | '/notifications'
    | '/planning'
    | '/profile'
    | '/reset-password'
    | '/settings'
    | '/sign-in'
    | '/sign-in-cover'
    | '/sign-in-illustration'
    | '/sign-in-link'
    | '/sign-up'
    | '/accounts/$accountId'
    | '/credit/credit-card'
    | '/credit/kpr'
    | '/credit/kta'
    | '/credit/overview'
    | '/credit/paylater'
    | '/dashboard/assets'
    | '/gamification/quests'
    | '/gamification/store'
    | '/gamification/streak'
    | '/planning/budget'
    | '/planning/goals'
    | '/planning/subscriptions'
    | '/tracker/audio'
    | '/tracker/file'
    | '/tracker/image'
    | '/tracker/input'
    | '/tracker/photo'
    | '/tracker/text'
    | '/credit/'
    | '/dashboard/'
    | '/planning/'
    | '/tracker/'
    | '/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R2StepVerificationRoute: typeof R2StepVerificationRoute
  R2StepVerificationCodeRoute: typeof R2StepVerificationCodeRoute
  AccountsRoute: typeof AccountsRouteWithChildren
  AchievementsRoute: typeof AchievementsRoute
  ActivityRoute: typeof ActivityRoute
  AssetsRoute: typeof AssetsRoute
  AuthLockRoute: typeof AuthLockRoute
  CreditRoute: typeof CreditRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  Error403Route: typeof Error403Route
  Error404Route: typeof Error404Route
  Error429Route: typeof Error429Route
  Error500Route: typeof Error500Route
  ErrorMaintenanceRoute: typeof ErrorMaintenanceRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  NotificationsRoute: typeof NotificationsRoute
  PlanningRoute: typeof PlanningRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignInCoverRoute: typeof SignInCoverRoute
  SignInIllustrationRoute: typeof SignInIllustrationRoute
  SignInLinkRoute: typeof SignInLinkRoute
  SignUpRoute: typeof SignUpRoute
  GamificationQuestsRoute: typeof GamificationQuestsRoute
  GamificationStoreRoute: typeof GamificationStoreRoute
  GamificationStreakRoute: typeof GamificationStreakRoute
  TrackerAudioRoute: typeof TrackerAudioRoute
  TrackerFileRoute: typeof TrackerFileRoute
  TrackerImageRoute: typeof TrackerImageRoute
  TrackerInputRoute: typeof TrackerInputRoute
  TrackerPhotoRoute: typeof TrackerPhotoRoute
  TrackerTextRoute: typeof TrackerTextRoute
  TrackerIndexRoute: typeof TrackerIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in-link': {
      id: '/sign-in-link'
      path: '/sign-in-link'
      fullPath: '/sign-in-link'
      preLoaderRoute: typeof SignInLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in-illustration': {
      id: '/sign-in-illustration'
      path: '/sign-in-illustration'
      fullPath: '/sign-in-illustration'
      preLoaderRoute: typeof SignInIllustrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in-cover': {
      id: '/sign-in-cover'
      path: '/sign-in-cover'
      fullPath: '/sign-in-cover'
      preLoaderRoute: typeof SignInCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-maintenance': {
      id: '/error-maintenance'
      path: '/error-maintenance'
      fullPath: '/error-maintenance'
      preLoaderRoute: typeof ErrorMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-500': {
      id: '/error-500'
      path: '/error-500'
      fullPath: '/error-500'
      preLoaderRoute: typeof Error500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-429': {
      id: '/error-429'
      path: '/error-429'
      fullPath: '/error-429'
      preLoaderRoute: typeof Error429RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-404': {
      id: '/error-404'
      path: '/error-404'
      fullPath: '/error-404'
      preLoaderRoute: typeof Error404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-403': {
      id: '/error-403'
      path: '/error-403'
      fullPath: '/error-403'
      preLoaderRoute: typeof Error403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit': {
      id: '/credit'
      path: '/credit'
      fullPath: '/credit'
      preLoaderRoute: typeof CreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-lock': {
      id: '/auth-lock'
      path: '/auth-lock'
      fullPath: '/auth-lock'
      preLoaderRoute: typeof AuthLockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2-step-verification-code': {
      id: '/2-step-verification-code'
      path: '/2-step-verification-code'
      fullPath: '/2-step-verification-code'
      preLoaderRoute: typeof R2StepVerificationCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2-step-verification': {
      id: '/2-step-verification'
      path: '/2-step-verification'
      fullPath: '/2-step-verification'
      preLoaderRoute: typeof R2StepVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker/': {
      id: '/tracker/'
      path: '/tracker'
      fullPath: '/tracker/'
      preLoaderRoute: typeof TrackerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning/': {
      id: '/planning/'
      path: '/'
      fullPath: '/planning/'
      preLoaderRoute: typeof PlanningIndexRouteImport
      parentRoute: typeof PlanningRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/credit/': {
      id: '/credit/'
      path: '/'
      fullPath: '/credit/'
      preLoaderRoute: typeof CreditIndexRouteImport
      parentRoute: typeof CreditRoute
    }
    '/tracker/text': {
      id: '/tracker/text'
      path: '/tracker/text'
      fullPath: '/tracker/text'
      preLoaderRoute: typeof TrackerTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker/photo': {
      id: '/tracker/photo'
      path: '/tracker/photo'
      fullPath: '/tracker/photo'
      preLoaderRoute: typeof TrackerPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker/input': {
      id: '/tracker/input'
      path: '/tracker/input'
      fullPath: '/tracker/input'
      preLoaderRoute: typeof TrackerInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker/image': {
      id: '/tracker/image'
      path: '/tracker/image'
      fullPath: '/tracker/image'
      preLoaderRoute: typeof TrackerImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker/file': {
      id: '/tracker/file'
      path: '/tracker/file'
      fullPath: '/tracker/file'
      preLoaderRoute: typeof TrackerFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker/audio': {
      id: '/tracker/audio'
      path: '/tracker/audio'
      fullPath: '/tracker/audio'
      preLoaderRoute: typeof TrackerAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning/subscriptions': {
      id: '/planning/subscriptions'
      path: '/subscriptions'
      fullPath: '/planning/subscriptions'
      preLoaderRoute: typeof PlanningSubscriptionsRouteImport
      parentRoute: typeof PlanningRoute
    }
    '/planning/goals': {
      id: '/planning/goals'
      path: '/goals'
      fullPath: '/planning/goals'
      preLoaderRoute: typeof PlanningGoalsRouteImport
      parentRoute: typeof PlanningRoute
    }
    '/planning/budget': {
      id: '/planning/budget'
      path: '/budget'
      fullPath: '/planning/budget'
      preLoaderRoute: typeof PlanningBudgetRouteImport
      parentRoute: typeof PlanningRoute
    }
    '/gamification/streak': {
      id: '/gamification/streak'
      path: '/gamification/streak'
      fullPath: '/gamification/streak'
      preLoaderRoute: typeof GamificationStreakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamification/store': {
      id: '/gamification/store'
      path: '/gamification/store'
      fullPath: '/gamification/store'
      preLoaderRoute: typeof GamificationStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamification/quests': {
      id: '/gamification/quests'
      path: '/gamification/quests'
      fullPath: '/gamification/quests'
      preLoaderRoute: typeof GamificationQuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/assets': {
      id: '/dashboard/assets'
      path: '/assets'
      fullPath: '/dashboard/assets'
      preLoaderRoute: typeof DashboardAssetsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/credit/paylater': {
      id: '/credit/paylater'
      path: '/paylater'
      fullPath: '/credit/paylater'
      preLoaderRoute: typeof CreditPaylaterRouteImport
      parentRoute: typeof CreditRoute
    }
    '/credit/overview': {
      id: '/credit/overview'
      path: '/overview'
      fullPath: '/credit/overview'
      preLoaderRoute: typeof CreditOverviewRouteImport
      parentRoute: typeof CreditRoute
    }
    '/credit/kta': {
      id: '/credit/kta'
      path: '/kta'
      fullPath: '/credit/kta'
      preLoaderRoute: typeof CreditKtaRouteImport
      parentRoute: typeof CreditRoute
    }
    '/credit/kpr': {
      id: '/credit/kpr'
      path: '/kpr'
      fullPath: '/credit/kpr'
      preLoaderRoute: typeof CreditKprRouteImport
      parentRoute: typeof CreditRoute
    }
    '/credit/credit-card': {
      id: '/credit/credit-card'
      path: '/credit-card'
      fullPath: '/credit/credit-card'
      preLoaderRoute: typeof CreditCreditCardRouteImport
      parentRoute: typeof CreditRoute
    }
    '/accounts/$accountId': {
      id: '/accounts/$accountId'
      path: '/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AccountsAccountIdRouteImport
      parentRoute: typeof AccountsRoute
    }
  }
}

interface AccountsRouteChildren {
  AccountsAccountIdRoute: typeof AccountsAccountIdRoute
}

const AccountsRouteChildren: AccountsRouteChildren = {
  AccountsAccountIdRoute: AccountsAccountIdRoute,
}

const AccountsRouteWithChildren = AccountsRoute._addFileChildren(
  AccountsRouteChildren,
)

interface CreditRouteChildren {
  CreditCreditCardRoute: typeof CreditCreditCardRoute
  CreditKprRoute: typeof CreditKprRoute
  CreditKtaRoute: typeof CreditKtaRoute
  CreditOverviewRoute: typeof CreditOverviewRoute
  CreditPaylaterRoute: typeof CreditPaylaterRoute
  CreditIndexRoute: typeof CreditIndexRoute
}

const CreditRouteChildren: CreditRouteChildren = {
  CreditCreditCardRoute: CreditCreditCardRoute,
  CreditKprRoute: CreditKprRoute,
  CreditKtaRoute: CreditKtaRoute,
  CreditOverviewRoute: CreditOverviewRoute,
  CreditPaylaterRoute: CreditPaylaterRoute,
  CreditIndexRoute: CreditIndexRoute,
}

const CreditRouteWithChildren =
  CreditRoute._addFileChildren(CreditRouteChildren)

interface DashboardRouteChildren {
  DashboardAssetsRoute: typeof DashboardAssetsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAssetsRoute: DashboardAssetsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PlanningRouteChildren {
  PlanningBudgetRoute: typeof PlanningBudgetRoute
  PlanningGoalsRoute: typeof PlanningGoalsRoute
  PlanningSubscriptionsRoute: typeof PlanningSubscriptionsRoute
  PlanningIndexRoute: typeof PlanningIndexRoute
}

const PlanningRouteChildren: PlanningRouteChildren = {
  PlanningBudgetRoute: PlanningBudgetRoute,
  PlanningGoalsRoute: PlanningGoalsRoute,
  PlanningSubscriptionsRoute: PlanningSubscriptionsRoute,
  PlanningIndexRoute: PlanningIndexRoute,
}

const PlanningRouteWithChildren = PlanningRoute._addFileChildren(
  PlanningRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R2StepVerificationRoute: R2StepVerificationRoute,
  R2StepVerificationCodeRoute: R2StepVerificationCodeRoute,
  AccountsRoute: AccountsRouteWithChildren,
  AchievementsRoute: AchievementsRoute,
  ActivityRoute: ActivityRoute,
  AssetsRoute: AssetsRoute,
  AuthLockRoute: AuthLockRoute,
  CreditRoute: CreditRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  Error403Route: Error403Route,
  Error404Route: Error404Route,
  Error429Route: Error429Route,
  Error500Route: Error500Route,
  ErrorMaintenanceRoute: ErrorMaintenanceRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  NotificationsRoute: NotificationsRoute,
  PlanningRoute: PlanningRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignInCoverRoute: SignInCoverRoute,
  SignInIllustrationRoute: SignInIllustrationRoute,
  SignInLinkRoute: SignInLinkRoute,
  SignUpRoute: SignUpRoute,
  GamificationQuestsRoute: GamificationQuestsRoute,
  GamificationStoreRoute: GamificationStoreRoute,
  GamificationStreakRoute: GamificationStreakRoute,
  TrackerAudioRoute: TrackerAudioRoute,
  TrackerFileRoute: TrackerFileRoute,
  TrackerImageRoute: TrackerImageRoute,
  TrackerInputRoute: TrackerInputRoute,
  TrackerPhotoRoute: TrackerPhotoRoute,
  TrackerTextRoute: TrackerTextRoute,
  TrackerIndexRoute: TrackerIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
