export const AVAILABLE_ICONS = [
  { value: 'smart-home', label: 'Home' },
  { value: 'building-bank', label: 'Bank' },
  { value: 'wallet', label: 'Wallet' },
  { value: 'cash', label: 'Cash' },
  { value: 'coin', label: 'Saving' },
  { value: 'chart-pie', label: 'Investment' },
  { value: 'credit-card', label: 'Credit Card' },
  { value: 'receipt', label: 'Bill' },

  { value: 'shopping-cart', label: 'Shopping' },
  { value: 'shopping-bag', label: 'Bag' },
  { value: 'package', label: 'Parcel' },
  { value: 'ice-cream', label: 'Food' },
  { value: 'coffee', label: 'Coffee' },
  { value: 'beer', label: 'Alcohol' },
  { value: 'pizza', label: 'Pizza' },
  { value: 'meat', label: 'Groceries' },

  { value: 'car', label: 'Transport' },
  { value: 'bus', label: 'Bus' },
  { value: 'bike', label: 'Bike' },
  { value: 'plane', label: 'Travel' },
  { value: 'map-pin', label: 'Location' },

  { value: 'heart', label: 'Health' },
  { value: 'pills', label: 'Medicine' },
  { value: 'dumbbell', label: 'Fitness' },
  { value: 'shirt', label: 'Clothes' },
  { value: 'scissors', label: 'Salon' },
  { value: 'user', label: 'Personal' },
  { value: 'users', label: 'Family' },
  { value: 'dog', label: 'Pet' },

  { value: 'device-gamepad', label: 'Games' },
  { value: 'ticket', label: 'Events' },
  { value: 'music', label: 'Music' },
  { value: 'camera', label: 'Photo' },
  { value: 'device-mobile', label: 'Phone' },
  { value: 'device-desktop', label: 'Computer' },
  { value: 'brand-netflix', label: 'Subscription' },

  { value: 'briefcase', label: 'Work' },
  { value: 'book', label: 'Education' },
  { value: 'school', label: 'School' },
  { value: 'tools', label: 'Maintenance' },
  { value: 'bulb', label: 'Idea' },

  { value: 'bolt', label: 'Electricity' },
  { value: 'droplet', label: 'Water' },
  { value: 'wifi', label: 'Internet' },
  { value: 'gift', label: 'Gift' },
  { value: 'star', label: 'Important' },
  { value: 'hash', label: 'Misc' },
]
